openapi: 3.0.3
info:
  title: Products API
  description: Products API
  version: 1.0.0

paths:
  /api/v1/products:
    get:
      summary: Get product information
      description: Returns a list of products with basic information
      responses:
        '200':
          $ref: '#/components/responses/200_OK_Products'
  /api/v1/products/{id}:
    get:
      summary: Get product information by Id
      description: Returns a product with a given Id
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        '200':
          $ref: '#/components/responses/200_OK_Product'
        '404':
          $ref: '#/components/responses/404_Not_Found'

components:
  parameters:
    ProductId:
      name: id
      in: path
      description: Product Id
      required: true
      schema:
        type: integer
  responses:
    200_OK_Products:
      description: A list of products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
    200_OK_Product:
      description: A product with given Id found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    404_Not_Found:
      description: A product with given Id found

  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Sample Product"
