openapi: 3.0.3
info:
  title: Products API
  description: Products API
  version: 1.0.0

paths:
  /api/v1/products:
    get:
      summary: Get product information
      description: Returns a list of products with basic information
      responses:
        '200':
          $ref: '#/components/responses/ProductsResponse200'

components:
  responses:
    ProductsResponse200:
      description: A list of products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Sample Product"
